#/*******************************************************************************************************#
#Las excepciones se configuran especificando los par치mentros mostrados en la excepci칩n de ejemplo "E1"
#Si desea incluir internacionalizaci칩n a los atributos de la excepci칩n debe sustituir los valores de los
#parametros "mensaje" y "descripcion" por el codigo del mensaje especificado en los archivos
#translatesexcepciones.* de la carpeta config/traslations, ejemplo:
#        E1:
#            mensaje: integrator.excepciones.E1.mensaje
#            descripcion: integrator.excepciones.E1.descripcion
#/*******************************************************************************************************#

excepciones:
    excepciones:
        E1:
            mensaje: integrator.excepciones.E1.mensaje
            descripcion: integrator.excepciones.E1.descripcion
