restRoute_usuario:
    pattern: '/api/integrator/usuario/{id}'
    methods: [GET]
    options: { id: UCI\Boson\PortalBundle\Model\Usuario }
    properties: {  }
restRoute_recurso:
    pattern: '/api/integrador/recurso/{id}'
    methods: [GET]
    options: { id: UCI\Boson\IntegratorBundle\Model\Recurso }
    properties: {  }
restRoute_servicio:
    pattern: '/api/integrador/servicio/{id}'
    methods: [GET]
    options: { id: UCI\Boson\IntegratorBundle\Model\Service }
    properties: {  }
restRoute_accion:
    pattern: '/api/Gestion/accion/{id}'
    methods: [PUT, POST]
    options: { id: UCI\Boson\TrazasBundle\Entity\hisAccion }
    properties: { idTraza: integer, fecha: string, hora: string, usuario: string, ipHost: string, rol: string, referencia: string, controlador: string, accion: string, inicio: string, falla: string }
restRoute_trazas_rendimiento:
    pattern: '/api/trazas/trazas_rendimiento/{id}'
    methods: [PATCH, POST]
    options: { id: UCI\Boson\TrazasBundle\Entity\hisRendimiento }
    properties: { idTraza: integer, tiempoEjecucion: float, memoria: float }
restRoute_live:
    pattern: '/api/portal/live/{id}'
    methods: [PATCH, PUT, GET]
    options: { id: UCI\Boson\PortalBundle\Entity\Live }
    properties: { id: integer, dataEffect: string, dataEasing: string }
restRoute_tilegroup:
    pattern: '/api/portal/tilegroup/{id}'
    methods: [PATCH, PUT, GET]
    options: { id: UCI\Boson\PortalBundle\Entity\TileGroup }
    properties: { id: integer, active: boolean, size: integer, title: string }
restRoute_tilegroup_myTiles:
    pattern: '/api/portal/tilegroup/{id}/myTiles/{idmyTiles}'
    methods: [PATCH, PUT, GET]
    options: { id: UCI\Boson\PortalBundle\Entity\TileGroup, idmyTiles: UCI\Boson\PortalBundle\Entity\Tile }
    properties: { id: integer, active: boolean, selected: boolean, backgroung: string, size: string, badge: string, statusBrand: string }
restRoute_tilegroup_myTiles_contents:
    pattern: '/api/portal/tilegroup/{id}/myTiles/{idmyTiles}/contents/{idcontents}'
    methods: [PATCH, PUT, GET]
    options: { id: UCI\Boson\PortalBundle\Entity\TileGroup, idmyTiles: UCI\Boson\PortalBundle\Entity\Tile, idcontents: UCI\Boson\PortalBundle\Entity\Content }
    properties: { id: integer }
restRoute_content:
    pattern: '/api/portal/content/{id}'
    methods: [PATCH, PUT, GET]
    options: { id: UCI\Boson\PortalBundle\Entity\Content }
    properties: { id: integer }
restRoute_tile:
    pattern: '/api/portal/tile/{id}'
    methods: [PATCH, PUT, GET]
    options: { id: UCI\Boson\PortalBundle\Entity\Tile }
    properties: { id: integer, active: boolean, selected: boolean, backgroung: string, size: string, badge: string, statusBrand: string }
restRoute_tile_contents:
    pattern: '/api/portal/tile/{id}/contents/{idcontents}'
    methods: [PATCH, PUT, GET]
    options: { id: UCI\Boson\PortalBundle\Entity\Tile, idcontents: UCI\Boson\PortalBundle\Entity\Content }
    properties: { id: integer }
