hello_page:
     pattern: /hello/page
     defaults: { _controller: "IntegratorBundle:Integrator:hello" }

integrator_deps:
     type: rest
     prefix: /dependency
     resource: UCI\Boson\IntegratorBundle\Controller\DependencyController

get_api_rest:
    pattern: /api/
    defaults: { _controller: "IntegratorBundle:RestService:apiRest"}

verb_controller:
    resource: "@IntegratorBundle/Controller/RestServiceController.php"
    type: annotation
