hello_page:
     pattern: /hello/page
     defaults: { _controller: "IntegratorBundle:Integrator:hello" }

NelmioApiDocBundle:
     resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
     prefix:   /api/doc

integrator_deps:
     type: rest
     prefix: /dependency
     resource: UCI\Boson\IntegratorBundle\Controller\DependencyController
