parameters:
#    integrator.example.class: UCI\Boson\IntegratorBundle\Example

services:
#    integrator.example:
#        class: %integrator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     integrator.reader:
         class: IntegratorBundle\Integrator\Configurator\XmlConfigurationReader
         arguments: [ %deps%, %resolved% ]
     integrator.writer:
         class: IntegratorBundle\Integrator\Configurator\XmlConfiguratorWriter
         arguments: [ %deps%, %resolved% ]
     integrator.dependency.manager:
         class: IntegratorBundle\Integrator\Manager\DependencyManager
         arguments: [ @integrator.reader, @integrator.writer ]
     integrator.resolved.manager:
         class:  IntegratorBundle\Integrator\Manager\ResolvedManager
         arguments: [ @integrator.reader, @integrator.writer ]


